set -g base-index 1

# Use vi-style keybindings in copy mode
setw -g mode-keys vi

# Resize panes using Prefix + Alt + hjkl
bind C-h resize-pane -L 5    # Resize left
bind C-j resize-pane -D 5    # Resize down
bind C-k resize-pane -U 5    # Resize up
bind C-l resize-pane -R 5    # Resize right

# Binding to move a window
bind-key m command-prompt "movew"

## List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'dracula/tmux'

# Match the bar to the Starship purple; use a deeper purple for the active tab.
set -g @dracula-colors 'gray="#bb9af7"; cyan="#bb9af7"; dark_purple="#987bc7"; white="#282a36"; network_blue="#8be9fd"'

# Use Dracula’s original cyan-blue for the Ethernet/network section.
set -g @dracula-network-colors "network_blue dark_gray"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
